sudo: false

language: php

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - tests/_cache
    - tests/_data

before_script:
  - composer update --dev --no-interaction